### ISSUE TITLE
Comments not working on website

### ISSUE THREAD

**Issue by TehPsychedelic** [binfalse/binfalse.de#2]
Hello,

I stumbled upon your blog via some old article about file compression but took a look at the staticman article as well, however, testing on two different articles, the same result, comments are not posted (doesn't make a difference if I leave URL out or not for example).
I'm basically greeted with this page:
`{"success":false,"errorCode":"INVALID_VERSION"}`

**Comment by binfalse** [comment]
Thanks for reporting! Indeed it has not been working...
The official staticman instances don't seem to be really stable, already needed to switch stuff a few times. Thus, I decided to run my own staticman, which also improves in terms of privacy :)
